version: 2
sources:
  - name: sales
    database: salesdata
    schema: sales
    tables:
      - name: customers
      - name: orders
        columns:
          - name: STATUS
            tests:
              - accepted_values:
                  values:
                    - 'returned'
                    - 'completed'
                    - 'return_pending'
                    - 'shipped'
                    - 'placed'
  - name: purchases
    database: salesdata
    schema: purchases
    tables:
      - name: payment
